/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package javaapplication1;

import java.io.BufferedWriter;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Wajahat Qazi
 */
public class Manage_Bookings extends javax.swing.JFrame {

    /**
     * Creates new form Manage_Bookings
     */
    public Manage_Bookings() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setBackground(new java.awt.Color(0, 0, 0, 100));
        jButton3.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(102, 102, 102));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/Presentation1/Approve.png"))); // NOI18N
        jButton3.setText("Approve");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 600, 150, 50));

        jButton2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 102, 102));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/Presentation1/decline.png"))); // NOI18N
        jButton2.setText("Decline");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 600, 140, 50));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/Presentation1/HOME.png"))); // NOI18N
        jButton4.setBorderPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 50));

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jTable1.setShowGrid(true);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 1240, 240));

        jButton1.setBackground(new java.awt.Color(153, 204, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/Presentation1/VAB.png"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 204, 255)));
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 520, 420, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/Presentation1/Slide4.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         
        String filePath="Booking_Data.txt";
         File file=new File(filePath);
 

         try{
             BufferedReader br=new BufferedReader(new FileReader(file));
             String firstLine=br.readLine().trim();
             String[] columnsName=firstLine.split("/");
             DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
             model.setColumnIdentifiers(columnsName);
                 
             
             String line = "";
while(line != null) {
     line = br.readLine().trim();
     if(line != null) {
           Object[] dataRow = line.split(",");
           model.addRow(dataRow);
     }
}
                
         }
         catch(Exception ex){

         }
         
         
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
          TableModel model1 = jTable1.getModel();
          int SelectedRowIndex = jTable1.getSelectedRow();
     int indexs[] = jTable1.getSelectedRows();
     Object row[] = new Object[12];
      for(int i = 0; i < indexs.length; i++)
        {
            row[0] = model1.getValueAt(indexs[i], 0);
            row[1] = model1.getValueAt(indexs[i], 1);
            row[2] = model1.getValueAt(indexs[i], 2);
            row[3] = model1.getValueAt(indexs[i], 3);
            row[4] = model1.getValueAt(indexs[i], 4);
            row[5] = model1.getValueAt(indexs[i], 5);
            row[6] = model1.getValueAt(indexs[i], 6);
            row[7] = model1.getValueAt(indexs[i], 7);
            row[8] = model1.getValueAt(indexs[i], 8);
            row[9] = model1.getValueAt(indexs[i], 9);
            row[10] = model1.getValueAt(indexs[i], 10);
            row[11] = model1.getValueAt(indexs[i], 11);
        }
      String name =(String) row[0];
      
      String arr=Arrays.toString(row);
       
   File file  = new File("Booking_Data.txt");
        try {
            BufferedReader br = new BufferedReader (new FileReader (file) ) ;
            String [] rec;
            String Status_old, Status_New;
            Object [] allRec = br . lines () . toArray () ;
            for (int i =1; i < allRec. length; i++) {
                rec = allRec [i] . toString () . trim() .split(",");
                if (rec[0].equals(name)) {
                    Status_old = rec[12];
                    Status_New = "Declined & Refunded";
                    rec[12] = Status_New;
                    String newrec="";
                    for (int j=0; j<rec. length; j++) {
                        newrec = newrec+rec [j]+",";    
                    }
                    allRec [i]= newrec;
                    
                } 
                           
            }
            BufferedWriter bw = new BufferedWriter (new FileWriter (file) ) ;
            for (int i=0; i<allRec. length; i++) {
                System.out.println("Rec["+i+"]: "+allRec[i]) ;
                bw . write (allRec[i]+"\n") ;
                
                
            }
            bw . close ( ) ;
            br . close () ;
          JOptionPane.showMessageDialog(null,"Booking Declined & Refunded Successfully");
            
            
            
        } catch (Exception e) {
        }
   
        
    }//GEN-LAST:event_jButton2ActionPerformed



    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        TableModel model1 = jTable1.getModel();
     int indexs[] = jTable1.getSelectedRows();
     Object row[] = new Object[12];
      for(int i = 0; i < indexs.length; i++)
        {
            row[0] = model1.getValueAt(indexs[i], 0);
            row[1] = model1.getValueAt(indexs[i], 1);
            row[2] = model1.getValueAt(indexs[i], 2);
            row[3] = model1.getValueAt(indexs[i], 3);
            row[4] = model1.getValueAt(indexs[i], 4);
            row[5] = model1.getValueAt(indexs[i], 5);
            row[6] = model1.getValueAt(indexs[i], 6);
            row[7] = model1.getValueAt(indexs[i], 7);
            row[8] = model1.getValueAt(indexs[i], 8);
            row[9] = model1.getValueAt(indexs[i], 9);
            row[10]= model1.getValueAt(indexs[i], 10);
            row[11]= model1.getValueAt(indexs[i], 11);
        }
      
      String arr=Arrays.toString(row);
      String name =(String) row[0];
      
      File file  = new File("Booking_Data.txt");
        try {
            BufferedReader br = new BufferedReader (new FileReader (file) ) ;
            String [] rec;
            String Status_old, Status_New;
            Object [] allRec = br . lines () . toArray () ;
            for (int i =1; i < allRec. length; i++) {
                rec = allRec [i] . toString () . trim() .split(",");
                if (rec[0].equals(name)) {
                    Status_old = rec[12];
                    Status_New = "Approved";
                    rec[12] = Status_New;
                    String newrec="";
                    for (int j=0; j<rec. length; j++) {
                        newrec = newrec+rec [j]+",";    
                    }
                    allRec [i]= newrec;
                    
                } 
                           
            }
            BufferedWriter bw = new BufferedWriter (new FileWriter (file) ) ;
            for (int i=0; i<allRec. length; i++) {
                System.out.println("Rec["+i+"]: "+allRec[i]) ;
                bw . write (allRec[i]+"\n") ;
                
                
            }
            bw . close ( ) ;
            br . close () ;
          JOptionPane.showMessageDialog(null,"Booking Approved Successfully");
            
            
            
        } catch (Exception e) {
        }
   
    }//GEN-LAST:event_jButton3ActionPerformed

    
    
    
    
    
    

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Admin_Options obj=new Admin_Options();
        obj.setVisible(true);
        dispose();

    }//GEN-LAST:event_jButton4ActionPerformed

    
    


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manage_Bookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manage_Bookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manage_Bookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manage_Bookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manage_Bookings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
